### ISSUE TITLE
`memoryUsed` is not realtime

### ISSUE THREAD

**Issue by simfeng** [anderskm/gputil#6]
code as below
```
g0 = GPUtil.getGPUs()[0]
g0.memoryUsed  # output 11768.0
```

but, the `nvidia-smi` shows
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN Xp            Off  | 00000000:02:00.0 Off |                  N/A |
| 23%   33C    P8    16W / 250W |    171MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN Xp            Off  | 00000000:82:00.0 Off |                  N/A |
| 23%   31C    P8    10W / 250W |     10MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

`memoryUsed` is not realtime, however, after I redo `g0 = GPUtil.getGPUs()[0]`, the output changed.

**Comment by anderskm** [comment]
Yes, the attributes of GPUs (including `memoryUsed`) returned using `getGPUs()` are only updated, when `getGPUs()` are called. `GPUtil` was not written with realtime in mind. It was written to help identify and select unoccupied GPUs. As such, it was only considered nesseccary to acquire a snapshot of the state of the GPUs, rather than continuous ("realtime") measurements of their states.

If you require continuous measurements of the GPUs, I suggest writing a wrap-around code, which calls `GPUtil.getGPUs()` as frequent as you require.

There are currently no plans for rewriting the `GPUtil` to include continuous measurements of the GPUs. In short, I am closing this issue, as I don't really consider it an issue.
